# Generated by Django 3.2.2 on 2021-06-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emppersonal',
            table='personal_info',
        ),
    ]
