# Generated by Django 3.2.2 on 2021-07-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emps', '0003_emppersonal_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppersonal',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='emppersonal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emppersonal',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
