# Generated by Django 3.2.2 on 2021-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0005_auto_20210706_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonal',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
