# Generated by Django 3.2.2 on 2021-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0006_alter_emppersonal_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emppersonal',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
