# Generated by Django 3.2.2 on 2021-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0007_alter_emppersonal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emppersonal',
            name='document',
            field=models.FileField(default='', upload_to='media'),
        ),
    ]
